### ISSUE TITLE
user control of optimizer output

### ISSUE THREAD

**Issue by martinrd3D** [EchoRLiu/robustGarch#11]
The user should be able to control showing or not showing the iterations below:

fitBM <- robGarch(ret, methods = "BM", optimizer_x0 = optInit)
##
## solnp--> Completed in 2 iterations

Also, what is the fourth parameter above?  Is this optimizer specific, to the user has to be told to see the optimizer manual

**Comment by EchoRLiu** [comment]
To silent the Rsolnp, you can use `fitBM <- robGarch(ret, methods = "BM", optimizer_x0 = optInit, optimizer_control = list(trace=0))`
