### ISSUE TITLE
fix `rtn.rda` type and documentation

### ISSUE THREAD

**Issue by dan9401** [EchoRLiu/robustGarch#18]
I'm in the process of updating documentation regarding #17 , and encountered a `roxygen` issue due to the `GSPC` dataset name.

In short, the loaded object name by `data(rtn)` needs to be the same name as last line in `data.R`. 

- [x] decide if we want to use `rtn` or `gspc`
- [x] Change file name, object name and documentation accordingly
- [x] Add explanation of `^GSPC` ticker
- [x] Change `rtn` data type to be `xts`? (or am I missing something)

I would suggest to create a branch from [17-change-class-name-to-robustgarch](https://github.com/EchoRLiu/robustGarch/tree/17-change-class-name-to-robustgarch) (d1b80de) to finish this and merge it back to [17-change-class-name-to-robustgarch](https://github.com/EchoRLiu/robustGarch/tree/17-change-class-name-to-robustgarch).

**Comment by EchoRLiu** [comment]
I think with gspc it would be more informative, perhaps gspc-rtn.xts?

**Comment by EchoRLiu** [comment]
a small idea: should we update the data with the most current data? perhaps with more years? currently it is around 13 years

**Comment by dan9401** [comment]
Good point, let's do that, how did you source it last time?
