### ISSUE TITLE
gspc structure causing issue 

### ISSUE THREAD

**Issue by EchoRLiu** [EchoRLiu/robustGarch#27]
I changed the data back to the old format as it runs when testing the without global variables code

but when building document, got the following error

`==> devtools::check()
══ Documenting ═════════════════════════════════════════════════════════════════════════════════════
ℹ Updating robustGarch documentation
ℹ Loading robustGarch
Error: 'gspc' is not an exported object from 'namespace:robustGarch'
Execution halted
Exited with status 1.`

When changed back to .rda without dates, it causes the following issue.

**Comment by dan9401** [comment]
@EchoRLiu, I assume this will be fixed together with the remaining #23 issues in PR #32.
