### ISSUE TITLE
Extended `R CMD check` issue resolving

### ISSUE THREAD

**Issue by EchoRLiu** [EchoRLiu/robustGarch#28]
- [x] fixed the S3 warnings themselves, but documentation need to be added
- [x] Fix `.Rd` files (should come from `.R`)

_Originally posted by @dan9401 in https://github.com/EchoRLiu/robustGarch/issues/23#issuecomment-2291249170_

**Comment by dan9401** [comment]
@EchoRLiu, I believe these are fixed in PR #31.

Let's close the issue if those are what you meant with the comments.

**Comment by dan9401** [comment]
1. [R package book reference for s3](https://r-pkgs.org/R-CMD-check.html#r-code)
2. If `R CMD check` hangs on `* checking use of S3 registration ...` in docker, it could be that you're running in headless mode and it needs a display. This [stackoverflow answer](https://stackoverflow.com/questions/66150399/r-package-check-stuck-on-checking-use-of-s3-registration) is not helpful.
