### ISSUE TITLE
exporting functions deicision

### ISSUE THREAD

**Issue by EchoRLiu** [EchoRLiu/robustGarch#29]
un-exported the internal functions but maybe still need a careful look to decide whether they should be exported - especially the rho function

_Originally posted by @dan9401 in https://github.com/EchoRLiu/robustGarch/issues/23#issuecomment-2291249170_

**Comment by dan9401** [comment]
I think for long term, this is the same thing as in issue #24.

For the short term, this will be included in PR #32 updates, we can close this when #32 is merged.

**Comment by dan9401** [comment]
> I think for long term, this is the same thing as in issue #24.
> 
> For the short term, this will be included in PR #32 updates, we can close this when #32 is merged.

Decided to fix the rest in #24.
