### ISSUE TITLE
add-action-rules

### ISSUE THREAD

**Issue by EchoRLiu** [EchoRLiu/robustGarch#33]

**Comment by EchoRLiu** [comment]
also: change merge auto close issue

**Comment by EchoRLiu** [comment]
a reference for the possible status check missing issue: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks

**Comment by dan9401** [comment]
Prevented the issue from being closed automatically when PR merged. In Projects -> Workflows.

**Comment by dan9401** [comment]
* Give the job names in `{action}.yaml` a static part allows GitHub to find the jobs (checks).
* If the name is fully static, the config will automatically be tagged in the job name
* Currently setting up the check requirements in rulesets (new feature 2023), could possibly also set it in branch automation.
