### ISSUE TITLE
Organize `robGarch` output properties

### ISSUE THREAD

**Issue by dan9401** [EchoRLiu/robustGarch#38]
Right now the return of the `robGarch` function has close to 20 output properties. Let's reorganize the output (probably just using lists) to have fewer properties and meaningful names on the 1st-level.

**Comment by EchoRLiu** [comment]
- use objects to combine some outputs

**Comment by robustport** [comment]
Specifically:  (1) Combine optimizer, optimizer_x0, optimizer_control, optimizer_result into a list named optDetails or optimizerDetails (I prefer camelCase/CamelCase, but if you prefer underscore, you can just interpret my camelCase as underscore). (2) data_name is redundant and can be deleted, (3) Change fixed_pars to tuningPars (4) Change methods to fitMethod, and return this as an output component, (5) Maybe we don't need to return yt, and if we do, it should be y_t, (6) Change observed_I to infoMatrix, (7) objective should be added to the optimizer list, (8) Delete time_elapsed (the R user can always do this outside the function, (9) put message in the optDetails list, (10) coefficients are missing and should be added, (11) standard_error, t_value, and p_value should be deleted, and made available via the summary method.
