### ISSUE TITLE
Allow standard GARCH(1,1) fit

### ISSUE THREAD

**Issue by dan9401** [EchoRLiu/robustGarch#39]
* See if simply changing the some of the input parameters will converge our regression to a standard GARCH(1,1)
* If not, we can create a conditional parameter to call `rugarch` underneath if specified.

**Comment by robustport** [comment]
I will try to check this in the next day or two.

**Comment by robustport** [comment]
I have checked this, and robGarch with large robustness tuning parameters give parameter estimates very close to those of rugarch.  To see this, run the R script robGarchBMlargeRobparsVSrugarch.R in  our shared folder DougEchoDan.  So I will close this issue.
