### ISSUE TITLE
robGarch QML incorrect IGarch fit

### ISSUE THREAD

**Issue by robustport** [EchoRLiu/robustGarch#45]
robGarch with methods = QML always fits an IGarch model.  This needs to be fixed asap.  And in doing so, it will be useful to add a new argument IGarch = FALSE as default, and if the user chooses IGarch = TRUE, the the IGarch model is fit.

**Comment by EchoRLiu** [comment]
"robGarch with methods = QML always fits an IGarch model" this is actually not the case, but we will implement an option to support iGARCH=True, where alpha+beta=1 is enforced.
